'feat/ms 4619 add lifecycle only for medication and healthcareelement'
taktik/icure-backend pull request #229
Opened 2020-11-25 17:21 UTC by DylanFriedrich

2020-11-25 17:24 UTC, DylanFriedrich commented
Les deux merges ont déjà fait l'objet d'une PR

2020-12-04 11:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/taktik/icure-backend?pullRequest=229) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/taktik/icure-backend?pullRequest=229) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Hamsdam<br/>:x: DylanFriedrich<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/taktik/icure-backend?pullRequest=229) it.</sub>

2021-01-22 09:11 UTC, Hamsdam approved these changes

2021-01-22 10:07 UTC, aduchate requested changes

2021-01-22 10:07 UTC, aduchate commented on src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/smf/impl/v23g/SoftwareMedicalFileExport.kt
> +                                id = IDINSURANCE().apply { s = IDINSURANCEschemes.ID_INSURANCE; value = it.code.substring(0, 3); }
If you remove the check on the code length... This might crash

2021-01-22 10:07 UTC, aduchate commented on src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/smf/impl/v23g/SoftwareMedicalFileExport.kt
> +                    code.type == "MEDISPRING-REASON" -> CDCONTENT().apply {
We should have a config systems like for import to avoid hardcoding vendors modifications here

2021-01-22 10:07 UTC, aduchate commented on src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/v20131001/KmehrExport.kt
> +                if(isNihiiValid(nihii) && !nihii.isNullOrEmpty()) {
No. Fix isNihiiValid if it lets null or empty nihii pass through

2021-01-22 11:49 UTC, DylanFriedrich commented on src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/smf/impl/v23g/SoftwareMedicalFileExport.kt
> +                                id = IDINSURANCE().apply { s = IDINSURANCEschemes.ID_INSURANCE; value = it.code.substring(0, 3); }
I didn't remove it, juste dropped the check on the code length few line down. It allow to have an empty insurancy status. If we don't have the insurance element, EHvalidator will return a critical error.

2021-01-22 15:12 UTC, merged