Added support for versionned design documents
taktik/icure-backend pull request #259
Opened 2021-05-03 12:29 UTC by borkowmichal

2021-05-03 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/taktik/icure-backend?pullRequest=259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/taktik/icure-backend?pullRequest=259) before we can accept your contribution.<br/><hr/>**Michal Borkowski** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/taktik/icure-backend?pullRequest=259) it.</sub>

2021-05-11 08:31 UTC, aduchate requested changes

2021-05-12 12:49 UTC, borkowmichal commented on src/main/kotlin/org/taktik/icure/config/CouchDbConfig.kt
> +        val log = LogFactory.getLog("org.taktik.icure.config.WebClient")
I think it's better to have separate logger for the WebClients with and without timeouts. So this one I'd rather call it : `org.taktik.icure.config.WebClientWithTimeout` and as it's only used in this place it can stay inside this lambda no ?

2021-05-12 13:07 UTC, aduchate commented on src/main/kotlin/org/taktik/icure/config/CouchDbConfig.kt
> +        val log = LogFactory.getLog("org.taktik.icure.config.WebClient")
But I think this lambda is often called... Which means that we will end up with a lot loggers being allocated and de-allocated

2021-06-30 07:29 UTC, merged