IBE-15 Add identifiers tags and codes to healthcare party
taktik/icure-backend pull request #389
Opened 2022-05-16 14:49 UTC by LotuxPunk

2022-05-16 16:05 UTC, lisatr2812 requested changes

2022-05-16 16:52 UTC, LotuxPunk commented on src/main/kotlin/org/taktik/icure/asyncdao/impl/HealthcarePartyDAOImpl.kt
> +			.startKey(from)
I wasn't super awake apparently, I  take the contactdao implementation as reference, I'll change that. 😅

2022-05-16 16:56 UTC, LotuxPunk commented on src/main/kotlin/org/taktik/icure/domain/filter/hcparty/HealthcarePartyByTagCodeFilter.kt
> +interface HealthcarePartyByTagCodeFilter : Filter<String, HealthcareParty> {
I'm not sure about this one 
- The others filter of the same kind (Code and Tag) for other entity only handle single combinations of code and type.
- it'd maybe mess up with filters dsl in sdks (since you can already chain tagCode-tagType and codeCode-codeType by and operators)

2022-05-16 17:00 UTC, LotuxPunk commented on src/main/kotlin/org/taktik/icure/asynclogic/impl/filter/hcparty/HealthcarePartyByTagCodeFilter.kt
> +			var ids: HashSet<String>? = null
It's the same implementation in almost all filters.

I'm totally agree with you, but then do I change the implementation of the others ? 👀

2022-05-17 12:02 UTC, lisatr2812 requested changes

2022-05-17 12:02 UTC, lisatr2812 commented on src/main/kotlin/org/taktik/icure/entities/HealthcareParty.kt
> + * @property identifier The healthcareparty's identifiers.
_The healthcareparty's identifiers, used by the client to identify uniquely and unambiguously the HCP. However, iCure may not guarantee this uniqueness by itself : This should be done at the client side._

2022-05-17 12:02 UTC, lisatr2812 commented on src/main/kotlin/org/taktik/icure/services/external/rest/v1/dto/HealthcarePartyDto.kt
> +	@Schema(description = "The healthcareparty's identifiers.") val identifiers: List<IdentifierDto> = emptyList(),
_The healthcareparty's identifiers, used by the client to identify uniquely and unambiguously the HCP. However, iCure may not guarantee this uniqueness by itself : This should be done at the client side._

2022-05-17 12:02 UTC, lisatr2812 commented on src/main/kotlin/org/taktik/icure/services/external/rest/v2/dto/HealthcarePartyDto.kt
> +	@Schema(description = "The healthcareparty's identifiers.") val identifiers: List<IdentifierDto> = emptyList(),
_The healthcareparty's identifiers, used by the client to identify uniquely and unambiguously the HCP. However, iCure may not guarantee this uniqueness by itself : This should be done at the client side._

2022-05-17 12:43 UTC, lisatr2812 commented on src/main/kotlin/org/taktik/icure/asynclogic/impl/filter/hcparty/HealthcarePartyByTagCodeFilter.kt
> +				else -> healthcarePartyLogic.getEntityIds()
TODO

2022-05-17 12:55 UTC, lisatr2812 commented on src/main/kotlin/org/taktik/icure/asyncdao/impl/HealthcarePartyDAOImpl.kt
> +			.keys(tagKeys)
Oups... To satisfy tagType only search, you need to use startKey and endKey, my bad :-)

2022-05-18 09:12 UTC, lisatr2812 approved these changes

2022-05-18 09:12 UTC, merged