bugfix/MS-7774_ignore-files-exported-in-specific-directory-for-HealthOne
taktik/icure-backend pull request #392
Opened 2022-05-23 14:23 UTC by SkiiNox

HealthOne ont mis en place ceci pour éviter les problèmes de mémoire de leur logiciel lors de l'export de fichiers de plus de 20Mo. Ils exportent donc les fichiers de plus de 20Mo dans un dossier différent. Le problème c'est que le backend créer quand même un document vide dans ce cas-ci.

![image](https://user-images.githubusercontent.com/67685593/169841038-bee5eafb-c6fb-4106-8a31-79dacc329f7e.png)

2022-06-07 09:18 UTC, aduchate requested changes

2022-06-07 09:18 UTC, aduchate commented on src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/smf/impl/v23g/SoftwareMedicalFileImport.kt
> +		val services = trn.headingsAndItemsAndTexts?.filterIsInstance(LnkType::class.java)?.filter { it.type == CDLNKvalues.MULTIMEDIA && it.url?.subSequence(0,8) != "PmfFiles" }?.map { lnk ->
That is sooooooo ad hoc... It would be better to have an option that allows for skipping files with a regex or from a list

2022-06-20 12:40 UTC, lisatr2812 requested changes

2022-06-20 12:40 UTC, lisatr2812 commented on src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/smf/impl/v23g/SoftwareMedicalFileImport.kt
> +		val services = trn.headingsAndItemsAndTexts?.filterIsInstance(LnkType::class.java)?.filter { it.type == CDLNKvalues.MULTIMEDIA && it.url == null }?.map { lnk ->
Why did we change condition from this : 
`it.type == CDLNKvalues.MULTIMEDIA && it.url?.subSequence(0,8) != "PmfFiles"`
to this : 
`it.type == CDLNKvalues.MULTIMEDIA && it.url == null` ?

Condition is totally different. 

If you would like to exclude some services from being mapped, you should create a new argument to the function as Antoine was suggesting, and use a Regex Pattern 
For example : 
```
parseDocumentInTransaction(
		trn: TransactionType,
		author: User,
		v: ImportResult,
		language: String,
		mappings: Map<String, List<ImportMapping>>,
		saveToDatabase: Boolean,
		kmehrIndex: KmehrMessageIndex,
        checkDocumentValidityFct: (LnkType) -> Boolean = (lnk: LnkType) -> true
	) { 
       ....
       .filter { it.type == CDLNKvalues.MULTIMEDIA && checkDocumentValidityFct(it) }
       ...
   }
```

Where checkDocumentValidityFct is using Regex to filter only LnkType that are satisfying a specific URL format

2022-06-28 09:46 UTC, lisatr2812 approved these changes

2022-06-28 09:46 UTC, merged