MS-7793 filter out patient users (align legacy with kraken)
taktik/icure-backend pull request #411
Opened 2022-06-16 14:21 UTC by jeanbaptistedeborman

2022-06-17 11:47 UTC, jeanbaptistedeborman commented
This was not tested correctly. Needs more testing.

2022-06-18 07:51 UTC, lisatr2812 requested changes

2022-06-18 07:51 UTC, lisatr2812 commented on src/main/java/org/taktik/icure/logic/UserLogic.java
> +	PaginatedList<User> listUsers(PaginationOffset pagination, Boolean skipPatient);
Use a boolean primitive type instead of the Object one and rename it skipPatient**s**

2022-06-18 07:51 UTC, lisatr2812 commented on src/main/java/org/taktik/icure/logic/impl/UserLogicImpl.java
> +	public PaginatedList<User> listUsers(PaginationOffset pagination, Boolean skipPatient) {
Use a boolean primitive type instead of the Object one and rename it skipPatient**s**

2022-06-18 07:51 UTC, lisatr2812 commented on src/main/java/org/taktik/icure/logic/impl/UserLogicImpl.java
> +                        .filter(u -> !skipPatient || !Strings.isNullOrEmpty(u.getHealthcarePartyId()))
Using this filter, you will not only skip patients you will also exclude : 
- admin users; 
- device users; 
+ Negation makes your filter not clear : Use it the opposite way. 
Like this : 
`.filter(u -> skipPatients && !Strings.isNullOrEmpty(u.getPatientId))`

2022-06-18 07:51 UTC, lisatr2812 commented on src/main/java/org/taktik/icure/services/external/rest/v1/facade/UserFacade.java
> +            @ApiParam(value = "Skip patients", required = false) @QueryParam("skipPatient") Boolean skipPatient
Rename it skipPatient**s** (both queryParan and variable name) to ensure Kraken compatibility

2022-06-21 08:51 UTC, lisatr2812 approved these changes

2022-06-21 08:52 UTC, merged